### ISSUE TITLE
data url is empty  or unavailable

### ISSUE THREAD

**Issue by zhuhongyue** [yalesong/pvse#12]
When I run python `python download_gulp_mrw.py `,some data url is invalid.
```
jd4lXngPg4Z0c mp4 url is empty
2H8IBNL2Ae9kQ mp4 url is empty
XKyqwYgBLxha8 mp4 url is empty
http://media1.giphy.com/media/c84Hf3KIsQ1uo/giphy is no longer available!
http://media0.giphy.com/media/Y5lzSqen6Y8nK/giphy is no longer available!
```

**Comment by zhuhongyue** [comment]
After the command executed, the exception above occured.
``Exception: Some of the video files are missing ({}). Try downloading videos again or contact the author at yalesong@csail.mit.edu``

**Comment by yalesong** [comment]
Please try downloading the GIF files directly from [this link (19 GB)](https://drive.google.com/file/d/1Gcv4j-b2TkWLgSNF1Ye5zOa-LTG3mBcL).
