### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by pwy-cmd** [yalesong/pvse#5]
Thanks for your job!
Sorry to bother you again

When I run your eval.py program, no matter how small my batch_size_eval setting is, I find that the graphics memory keeps accumulating, which eventually causes the graphics card to run out of memory and the program fails. My graphics card is GTX1080TI 11G.

Any help would be appreciated. Thank you!

**Comment by yalesong** [comment]
That is possible with a single GPU machine. What model and dataset were you evaluating? Can you share your command line that you used to run eval.py so that I have better idea what you were trying to achieve?

**Comment by pwy-cmd** [comment]
Thank you for your reply！
In the evaluation process, I used the coco dataset which you provide in the prepare_coco_dataset.sh and the pretrained model in ResNet152. 
And the command line we used showing as follow:

H:\HJH\Polysemous Visual-Semantic Embedding for Cross-Modal Retrieval\pvse-master>python eval.py --data_name coco --num_embeds 2 --img_attention --txt_attention --ckpt ./ckpt/coco_pvse.pth
Loading dataset
loading annotations into memory...
Done (t=0.46s)
creating index...
index created!
Computing results... (eval_on_gpu=GPU)
Traceback (most recent call last):
  File "eval.py", line 289, in <module>
    metrics = evalrank(model, args, split='test')
  File "eval.py", line 213, in evalrank
    img_embs, txt_embs = encode_data(model, data_loader, args.eval_on_gpu)
  File "eval.py", line 34, in encode_data
    img_emb, txt_emb, _, _, _, _ = model.forward(img, txt, txt_len)
  File "I:\Python3.6\lib\site-packages\torch\nn\parallel\data_parallel.py", line 151, in forward
    replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
  File "I:\Python3.6\lib\site-packages\torch\nn\parallel\data_parallel.py", line 156, in replicate
    return replicate(module, device_ids, not torch.is_grad_enabled())
  File "I:\Python3.6\lib\site-packages\torch\nn\parallel\replicate.py", line 96, in replicate
    param_copies = _broadcast_coalesced_reshape(params, devices, detach)
  File "I:\Python3.6\lib\site-packages\torch\nn\parallel\replicate.py", line 79, in _broadcast_coalesced_reshape
    tensor_copies = Broadcast.apply(devices, *tensors)
  File "I:\Python3.6\lib\site-packages\torch\nn\parallel\_functions.py", line 21, in forward
    outputs = comm.broadcast_coalesced(inputs, ctx.target_gpus)
  File "I:\Python3.6\lib\site-packages\torch\cuda\comm.py", line 39, in broadcast_coalesced
    return torch._C._broadcast_coalesced(tensors, devices, buffer_size)
RuntimeError: CUDA out of memory. Tried to allocate 18.00 MiB (GPU 0; 11.00 GiB total capacity; 6.09 GiB already allocated; 8.82 MiB free; 2.62 GiB cached) (malloc at ..\c10\cuda\CUDACachingAllocator.cpp:267)
(no backtrace available)

Any help would be appreciated. Thank you!

**Comment by yalesong** [comment]
> Computing results... (eval_on_gpu=GPU)

It is strange to see `GPU` as a value to the variable `args.eval_on_gpu` as it should be Boolean; it should print `eval_on_gpu=False` by default unless you pass --eval_on_gpu as command line input. (see [this line](https://github.com/yalesong/pvse/blob/master/option.py#L52)). But I haven't tested it on Windows. Can you force the variable `args.eval_on_gpu` to be Boolean and make sure it is set to False?

**Comment by pwy-cmd** [comment]
Thank you very much for your reply, which is of great help to me. I have successfully run the code and the results are similar to those in your paper.
