### ISSUE TITLE
Not sure how MIL loss is computed

### ISSUE THREAD

**Issue by chinmay5** [yalesong/pvse#9]
First up, thank you so much for the wonderful code. I still have one issue which I am not able to understand from the code. In the code we are dealing with MIL loss but I am not sure how it is implemented using the MaxPool idea. This may be partly due to my lack of understanding about MIL itself. If there is any resource which you think can help me here, I shall be really grateful.

**Comment by yalesong** [comment]
Hi, thanks for the kind words! The MaxPool2d is there to compute the maximum similarity from each of the KxK embedding pairs. Note that in the paper we write it as the minimum over distances, which is the same as the maximum over similarities.
